(function(){'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let DATA=[],ACTIVE=[],filter='all',tab='search',mode='readable',timer=0,renderSeq=0,paintSeq=0;
let CODE_MAP=new Map(),CHILDREN=new Map(),REF_MAP=new Map();
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').replace(/Đ/g,'D').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const codeNorm=s=>(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');
const rawCode=s=>(s||'').toUpperCase().replace(/\s+/g,'');
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const getStore=k=>{try{return JSON.parse(localStorage.getItem(k)||'[]')}catch(e){return[]}},setStore=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}};
let fav=getStore('tt06_qd1849_favs'),recent=getStore('tt06_qd1849_recent');
const flagText={24:'Không dùng làm bệnh chính',25:'Không khuyến khích dùng làm bệnh chính',26:'Có mã cụ thể hơn',27:'Chỉ mã hóa nguyên nhân tử vong',28:'Chỉ có/chủ yếu ở nữ',29:'Chỉ có/chủ yếu ở nam'};
const isMain=x=>!x.cancelled&&![24,25,26,27].some(f=>x.f.includes(f));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1400)}
function copyText(t,msg){const done=()=>toast(msg||'Đã sao chép');const fallback=()=>{const e=document.createElement('textarea');e.value=t;e.style.position='fixed';e.style.opacity='0';document.body.appendChild(e);e.select();try{document.execCommand('copy')}catch(_e){}e.remove();done()};if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(t).then(done).catch(fallback);else fallback()}
function pool(){if(tab==='fav')return DATA.filter(x=>fav.includes(x._id));if(tab==='recent')return recent.map(id=>DATA.find(x=>x._id===id)).filter(Boolean);return DATA}
function filterOK(x){if(filter==='all')return true;if(filter==='main')return isMain(x);if(filter==='warn')return x.cancelled||x.f.length>0;if(filter==='new')return !!x.new;if(filter==='cancelled')return !!x.cancelled;if(filter==='female')return x.f.includes(28);if(filter==='male')return x.f.includes(29);if(filter==='death')return x.f.includes(27);return true}
function allWords(text,parts){for(const p of parts)if(!text.includes(p))return false;return true}
function textScore(x,nq,parts){let best=0;for(const f of x._directFields){if(!f)continue;if(f===nq)best=Math.max(best,9000);else if(f.startsWith(nq))best=Math.max(best,8500);else if(f.includes(nq))best=Math.max(best,8000);else if(parts.length>1&&allWords(f,parts))best=Math.max(best,7400)}if(best)return [best,'direct'];for(const f of x._relatedFields){if(!f)continue;if(f===nq)best=Math.max(best,6900);else if(f.startsWith(nq))best=Math.max(best,6500);else if(f.includes(nq))best=Math.max(best,6100);else if(parts.length>1&&allWords(f,parts))best=Math.max(best,5700)}return best?[best,'related']:[0,'']}
function parseRefs(text){const set=new Set(),up=(text||'').toUpperCase();let m;const er=/\b[A-Z][0-9]{2}(?:\.[0-9A-Z]{1,2})?[*†]?/g;while((m=er.exec(up)))set.add(codeNorm(m[0]));return Array.from(set)}
function nearestKnown(q){let t=q;while(t.length>3){t=t.slice(0,-1);if(CODE_MAP.has(t))return t}return ''}
function status(x){if(x.cancelled)return '<div class="status bad"><b>Mã bị hủy — không sử dụng</b>Có trong QĐ 4469 nhưng không còn trong TT06/2026.</div>';if(isMain(x))return '<div class="status"><b>Có thể dùng làm bệnh chính</b>Vẫn cần đối chiếu chẩn đoán thực tế và hồ sơ bệnh án.</div>';let t='Mã có cảnh báo',cl='warn',sub='Đọc hướng dẫn mã hóa trước khi sử dụng.';if(x.f.includes(24)){t='Không dùng làm bệnh chính';cl='bad'}else if(x.f.includes(25)){t='Không khuyến khích dùng làm bệnh chính';cl='bad'}else if(x.f.includes(26)){t='Cần chọn mã cụ thể hơn';sub='Không nên dùng mã nhóm nếu đã có mã 4/5 ký tự phù hợp với hồ sơ.'}else if(x.f.includes(27)){t='Chỉ dùng mã hóa nguyên nhân tử vong';cl='bad'}return `<div class="status ${cl}"><b>${t}</b>${sub}</div>`}
function badges(x){const a=[];if(x.cancelled)a.push('<span class="badge cancel">Mã bị hủy</span>');if(x.new)a.push('<span class="badge new">Mã mới TT06</span>');x.f.forEach(f=>a.push(`<span class="badge ${f===26?'purple':f===27?'gold':f===28||f===29?'cyan':''}">${esc(flagText[f]||('Cảnh báo '+f))}</span>`));if(x.c.includes('*'))a.push('<span class="badge cyan">Biểu hiện *</span>');if(x.c.includes('†'))a.push('<span class="badge gold">Căn nguyên †</span>');return a.length?`<div class="badges">${a.join('')}</div>`:''}
function childrenBlock(x){const kids=(CHILDREN.get(x._rc)||[]).filter(k=>!k.cancelled);if(!kids.length)return '';const usable=kids.filter(isMain),list=(usable.length?usable:kids);return `<details class="details children"><summary>▸ Gợi ý mã cụ thể hơn (${list.length.toLocaleString('vi-VN')})</summary><div class="child-list">${list.map(k=>`<button type="button" data-child="${esc(k.c)}"><code>${esc(k.c)}</code><span>${esc(k.n)}</span></button>`).join('')}</div></details>`}
function detail(x){const hierarchy=[x.ch,x.b,x.s1,x.s2,x.q].filter(Boolean).filter((v,i,a)=>a.indexOf(v)===i).join(' › '),guides=[x.gv,x.ge].filter(Boolean).join('\n\n');if(!hierarchy&&!guides)return '';return `<details class="details"><summary>▸ Xem phân cấp và hướng dẫn mã hóa</summary><div class="detail-body">${hierarchy?`<div class="field"><b>Phân cấp:</b> ${esc(hierarchy)}</div>`:''}${guides?`<div class="field"><b>Hướng dẫn mã hóa:</b>\n${esc(guides)}</div>`:''}</div></details>`}
function card(x,related){const saved=fav.includes(x._id),wrap=mode==='compact'?' compact':'';const action=x.cancelled?'<button class="btn disabled" type="button" disabled>Không dùng</button>':`<button class="btn primary" data-use="${esc(x._id)}">Dùng mã</button>`;return `<article class="card${related?' related':''}${x.cancelled?' cancelled':''}${wrap}"><div class="card-top"><div class="code">${esc(x.c)}</div><div class="name">${esc(x.n)}</div><button class="fav ${saved?'on':''}" data-fav="${esc(x._id)}">${saved?'★':'☆'}</button></div>${x.e?`<div class="english">${esc(x.e)}</div>`:''}<div class="source-row">${x.ch?`<span class="pill">${esc(x.ch)}</span>`:''}${x.b?`<span class="pill">${esc(x.b)}</span>`:''}${x.q&&x.q!==x.n?`<span class="pill">${esc(x.q)}</span>`:''}</div>${status(x)}${badges(x)}${childrenBlock(x)}${detail(x)}<div class="actions"><button class="btn" data-copy="${esc(x._id)}">Copy mã</button><button class="btn copyname" data-copyname="${esc(x._id)}">Copy mã + tên</button>${action}</div></article>`}
function sectionShell(title,related,total,banner){return `<section class="section ${related?'related':''}" data-section="${related?'related':'direct'}"><div class="section-title"><b>${title}</b><span>${total.toLocaleString('vi-VN')} mã</span></div>${banner||''}<div class="cards"></div></section>`}
function appendAll(section,arr,related,seq){if(!section||!arr.length)return;const target=section.querySelector('.cards');let i=0;const BATCH=80;function step(){if(seq!==paintSeq)return;const end=Math.min(i+BATCH,arr.length),frag=document.createDocumentFragment(),box=document.createElement('div');let html='';for(;i<end;i++)html+=card(arr[i],related);box.innerHTML=html;while(box.firstChild)frag.appendChild(box.firstChild);target.appendChild(frag);if(i<arr.length){(window.requestIdleCallback||function(cb){setTimeout(cb,8)})(step,{timeout:80})}}step()}
function codeResults(base,rawq,cq){let direct=[],related=[],corrected='',effective=cq;const baseSet=new Set(base.map(x=>x._id));let exact=(CODE_MAP.get(cq)||[]).filter(x=>baseSet.has(x._id));
  if(exact.length){const rq=rawCode(rawq);exact.sort((a,b)=>(rawCode(a.c)===rq?0:1)-(rawCode(b.c)===rq?0:1)||a.cancelled-b.cancelled||a._order-b._order);direct=exact.slice();const parent=exact.find(x=>!x.cancelled&&x.f.includes(26));if(parent){for(const k of CHILDREN.get(parent._rc)||[])if(baseSet.has(k._id)&&!direct.includes(k))direct.push(k)}}
  else if(cq.length<3){direct=base.filter(x=>x._rc.startsWith(cq)).sort((a,b)=>a._order-b._order)}
  else {const pref=base.filter(x=>x._rc.startsWith(cq));if(pref.length)direct=pref.sort((a,b)=>a._order-b._order);else{const near=nearestKnown(cq);if(near){effective=near;corrected=near;direct=(CODE_MAP.get(near)||[]).filter(x=>baseSet.has(x._id));const p=direct.find(x=>!x.cancelled&&x.f.includes(26));if(p)for(const k of CHILDREN.get(p._rc)||[])if(baseSet.has(k._id)&&!direct.includes(k))direct.push(k)}}}
  const seen=new Set(direct.map(x=>x._id));if(effective.length>=3){for(const x of REF_MAP.get(effective)||[]){if(baseSet.has(x._id)&&!seen.has(x._id)){related.push(x);seen.add(x._id)}}}
  return {direct,related,effective,corrected}}
function textResults(base,nq,parts){const direct=[],related=[];for(const x of base){const [s,t]=textScore(x,nq,parts);if(!s)continue;(t==='direct'?direct:related).push([s,x])}const sorter=(a,b)=>b[0]-a[0]||a[1].cancelled-b[1].cancelled||a[1]._order-b[1]._order;direct.sort(sorter);related.sort(sorter);return {direct:direct.map(z=>z[1]),related:related.map(z=>z[1]),effective:'',corrected:''}}
function render(){const seq=++paintSeq,q=$('#q').value.trim(),compact=q.replace(/\s+/g,''),nq=norm(q),cq=codeNorm(q),codeLike=/^[A-Za-z](?:[0-9]{0,2})(?:[.\-]?[0-9A-Za-z*†]{0,3})?$/.test(compact),parts=nq.split(' ').filter(Boolean),base=pool().filter(filterOK);let direct=[],related=[],corrected='',effective='';
  if(tab==='search'&&q){const r=codeLike&&cq?codeResults(base,q,cq):textResults(base,nq,parts);direct=r.direct;related=r.related;corrected=r.corrected;effective=r.effective}else if(tab!=='search')direct=base;
  const dt=direct.length,rt=related.length,total=dt+rt;$('#count').textContent=q?`${total.toLocaleString('vi-VN')} mã · trực tiếp ${dt} · liên quan ${rt}`:`${base.length.toLocaleString('vi-VN')} mã`;const root=$('#results');
  if(tab==='search'&&!q){root.innerHTML='<div class="empty"><div class="lotus">🪷</div><b>Nhập mã hoặc tên bệnh để tra cứu</b><p>Đã tích hợp mã hiện hành TT06, mã mới PL5, mã bị hủy PL4 và toàn bộ phân cấp/hướng dẫn có trong bảng Excel.</p></div>';return}
  if(!total){root.innerHTML='<div class="empty"><div class="lotus">🪷</div><b>Chưa tìm thấy mã phù hợp</b><p>Hãy kiểm tra lại ký tự mã hoặc nhập tên bệnh đầy đủ hơn.</p></div>';return}
  let top='';if(corrected){const shown=direct[0];top=`<div class="group-banner"><b>Không có mã ${esc(q.toUpperCase())} trong TT06/2026</b><small>Đã đối chiếu về mã gần nhất ${esc(shown?shown.c:effective)}. Không mở rộng sang các mã cùng nhóm không liên quan.</small></div>`}
  root.innerHTML=top+(dt?sectionShell(tab==='search'?'Mã trực tiếp':tab==='fav'?'Mã đã lưu':'Mã gần đây',false,dt,''):'')+(rt?sectionShell('Mã được nhắc trong hướng dẫn',true,rt,''):'');appendAll(root.querySelector('[data-section="direct"]'),direct,false,seq);appendAll(root.querySelector('[data-section="related"]'),related,true,seq)}
function schedule(){clearTimeout(timer);const seq=++renderSeq;timer=setTimeout(()=>{if(seq!==renderSeq)return;requestAnimationFrame(()=>{if(seq===renderSeq)render()})},18)}
function addRecent(id){recent=[id,...recent.filter(v=>v!==id)].slice(0,80);setStore('tt06_qd1849_recent',recent)}
document.addEventListener('click',e=>{const child=e.target.closest('[data-child]');if(child){$('#q').value=child.dataset.child;window.scrollTo({top:0,behavior:'smooth'});render();return}const b=e.target.closest('[data-fav],[data-copy],[data-copyname],[data-use]');if(!b)return;const id=b.dataset.fav||b.dataset.copy||b.dataset.copyname||b.dataset.use;if(b.dataset.fav){fav=fav.includes(id)?fav.filter(v=>v!==id):[id,...fav];setStore('tt06_qd1849_favs',fav);render();return}const x=DATA.find(y=>y._id===id);if(!x)return;if(b.dataset.copy)copyText(x.c,'Đã sao chép mã');else if(b.dataset.copyname)copyText(x.c+' — '+x.n,'Đã sao chép mã và tên');else if(!x.cancelled){copyText(x.c,'Đã chọn mã '+x.c);addRecent(id)}});
$('#q').addEventListener('input',schedule);$('#clear').addEventListener('click',()=>{$('#q').value='';$('#q').focus();render()});
$$('.chip').forEach(b=>b.addEventListener('click',()=>{$$('.chip').forEach(x=>x.classList.remove('on'));b.classList.add('on');filter=b.dataset.filter;render()}));
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('on'));b.classList.add('on');tab=b.dataset.tab;render()}));
$$('.mode-btn').forEach(b=>b.addEventListener('click',()=>{$$('.mode-btn').forEach(x=>x.classList.remove('on'));b.classList.add('on');mode=b.dataset.mode;render()}));
$('#topbtn').addEventListener('click',()=>window.scrollTo({top:0,behavior:'smooth'}));window.addEventListener('scroll',()=>$('#topbtn').classList.toggle('show',window.scrollY>650),{passive:true});
try{DATA=(window.ICD_TT06||[]).map((x,i)=>{x._order=i;x._rc=codeNorm(x.c);x._id=(x.cancelled?'old:':'cur:')+x.c;x._directFields=[norm(x.c),norm(x.s),norm(x.n),norm(x.e),norm(x.q),norm(x.qe)].filter(Boolean);x._relatedFields=[norm(x.ch),norm(x.b),norm(x.s1),norm(x.s2),norm(x.ce),norm(x.be),norm(x.s1e),norm(x.s2e),norm(x.ge),norm(x.gv)].filter(Boolean);x._refs=parseRefs((x.ge||'')+'\n'+(x.gv||''));return x});ACTIVE=DATA.filter(x=>!x.cancelled);
  for(const x of DATA){if(!CODE_MAP.has(x._rc))CODE_MAP.set(x._rc,[]);CODE_MAP.get(x._rc).push(x)}
  for(const x of ACTIVE){for(let k=3;k<x._rc.length;k++){const p=x._rc.slice(0,k);if(CODE_MAP.has(p)){if(!CHILDREN.has(p))CHILDREN.set(p,[]);CHILDREN.get(p).push(x)}}}
  for(const x of DATA)for(const r of x._refs){if(!REF_MAP.has(r))REF_MAP.set(r,[]);REF_MAP.get(r).push(x)}
  const active=ACTIVE.length,cancelled=DATA.length-active,newCount=ACTIVE.filter(x=>x.new).length,dc=$('#datasetCheck');if(dc){if(active===15844&&newCount===3928&&cancelled>=302)dc.textContent=`✓ 15.844 hiện hành · 3.928 mã mới · 303 mục PL4 / ${cancelled} mã duy nhất`;else{dc.textContent=`⚠ Dữ liệu: ${active} hiện hành · ${newCount} mới · ${cancelled} hủy`;dc.classList.add('bad')}}const p=new URLSearchParams(location.search);if(p.get('q'))$('#q').value=p.get('q');render()}catch(e){$('#count').textContent='Không đọc được dữ liệu';$('#results').innerHTML='<div class="empty"><div class="lotus">🪷</div><b>Lỗi dữ liệu nội bộ</b><p>Vui lòng cài lại ứng dụng.</p></div>'}
})();
